Feature/obasoro kunle
open-sauced/guestbook pull request #110
Opened 2023-10-04 01:32 UTC by Obasoro

## Description

- Add Obasoro kunle to the contibutors list

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-10-04 01:36 UTC, CBID2 requested changes
Thanks for your Pull Request @Obasoro! We've merged in some new PRs since you submitted. Can you merge the latest changes and resolve conflicts? If you need some help with that, check out this post: [Keeping Your Branch Up to Date and Handling Merge Conflicts While Waiting for PR Reviews](https://dev.to/opensauced/keeping-your-branch-up-to-date-and-handling-merge-conflicts-while-waiting-for-pr-reviews-3b3h).

2023-10-04 02:13 UTC, Obasoro commented
@CBID2 Thanks for the message. Just for better understanding `Can you merge the latest changes and resolve conflicts?`, would need some clarity on this.

2023-10-04 02:15 UTC, CBID2 commented
> @CBID2 Thanks for the message. Just for better understanding `Can you merge the latest changes and resolve conflicts?`, would need some clarity on this.

We mean to update your branch, but it looks like you did a force push instead.

2023-10-04 02:21 UTC, Obasoro commented
Thanks @CBID2. On mt `feature/obasoro-kunle` showing `This branch is not behind the upstream open-sauced:main
`. Trying to understand the next action.

2023-10-04 02:42 UTC, CBID2 commented
> Thanks @CBID2. On mt `feature/obasoro-kunle` showing `This branch is not behind the upstream open-sauced:main `. Trying to understand the next action.

Did my suggestion work @Obasoro?

2023-10-04 02:54 UTC, Obasoro commented
Thanks @CBID2 . Sometimes I don't want to get things messed up. Still learning the ropes and #Opensauce is place to get my skill sharpen and also my hands dirty

2023-10-04 02:55 UTC, CBID2 commented
> Thanks @CBID2 . Sometimes I don't want to get things messed up. Still learning the ropes and #Opensauce is place to get my skill sharpen and also my hands dirty

I updated my previous comment @Obasoro. Check it out.

2023-10-04 03:03 UTC, Obasoro commented
Do have to submit another pull request?

2023-10-04 03:14 UTC, CBID2 commented
> Do have to submit another pull request?

Let's wait for Bekah's response first.

2023-10-05 10:59 UTC, adiati98 requested changes
Hey @Obasoro,

I see that you haven't update your forked repo. That's why you still have conflicts.
Click the "Sync fork", then "Update branch". Next, update your local working branch.

I left you some comments here. After you updated your local working branch, please fix them first before we can merge your PR.

If you have questions do let us know :)

2023-10-05 10:59 UTC, adiati98 commented on README.md
> +=======
This should be generated once after you run the `npm run contributors:generate`.
But there is a duplication below.

Delete them both and run `npm run contributors:generate` after you added yourself in `.all-contributorsrc`.

2023-10-05 10:59 UTC, adiati98 commented on README.md
> +>>>>>>> 5aeb014... docs: add @obasoro as a contributor
The duplication.

2023-10-05 10:59 UTC, adiati98 commented on README.md
>  <!-- ALL-CONTRIBUTORS-BADGE:END -->
We don't want to modify this, but there's badge duplication here.
So, delete line 126-128 and 130.

2023-10-07 15:51 UTC, Obasoro commented
Added Obasoro Kunle manually.

2023-10-07 16:01 UTC, CBID2 commented
There's still merge conflicts on this branch @Obasoro. Have considered trying this method: https://blog.kaleidoscope.app/2022/04/12/resolving-merge-conflicts-in-vscode-with-kaleidoscope/

2023-10-07 16:56 UTC, closed without merging

2023-10-07 17:46 UTC, adiati98 commented
@Obasoro, is there any reason you close the PR and force-push your commits?

2023-10-08 13:55 UTC, Obasoro commented
@adiati98 I added everything back and thought everything was going work fine but failed so had to close it and create a new one.