docs: add @unpervertedkid as a contributor
open-sauced/guestbook pull request #145
Opened 2023-10-21 11:32 UTC by unpervertedkid

## Description
Practice open source contribution while taking the intro.opensauced.pizza course.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

2023-10-22 07:08 UTC, adiati98 commented
Hi @unpervertedkid,
Thank you for your PR!

We have merged a PR before yours. So please [resolve the conflicts](https://github.com/open-sauced/guestbook#getting-started) first before we can merge yours :)

2023-10-22 10:24 UTC, unpervertedkid commented
@adiati98 Done!
You can go ahead with the review

2023-10-22 10:37 UTC, adiati98 requested changes
Hey @unpervertedkid,
Please fix this before we can merge your PR :)

2023-10-22 10:37 UTC, adiati98 commented on .all-contributorsrc
> +     {
You added a space in these lines. Please remove the space.

2023-10-23 15:43 UTC, adiati98 commented
Hey @unpervertedkid 
As we're waiting for your changes, we've merged in another PR. So, please resolve the conflicts first. Thank you 🙂

2023-10-23 16:27 UTC, unpervertedkid commented
@adiati98  Can you check it now? Sorry I took a while to respond.

2023-10-23 17:31 UTC, adiati98 approved these changes
Well done, @unpervertedkid! 🙌
Thank you for the changes! 😄

If you haven't, come and join our community [Discord](https://discord.com/invite/U2peSNf23P). 😊
Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕 

![git merge GIF](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

2023-10-23 17:31 UTC, merged