docs: add @ijayhub as a contributor
open-sauced/guestbook pull request #216
Opened 2024-01-20 08:21 UTC by ijayhub

## Description

## What type of PR is this? (check all applicable)

- [ ] 🤝 Add a contributor

## Contributors checklist (check all applicable)

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) section.

- [ ] ✅ Yes

### How did you add yourself as a contributor?

- [ ] 🤖 With CLI

#### If you added yourself manually, did you follow the [emoji key and contribution types](https://allcontributors.org/docs/en/emoji-key) to fill in the value?

- [ ] ✅ Yes
- [ ] ❌ No

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?
-
- [ ] ❌ No

## Added to documentation?
- [ ] 🙅 no documentation needed

## Screenshot

## [optional] What GIF best describes this PR or how it makes you feel?
![ClaireDancingGIF](https://github.com/open-sauced/guestbook/assets/66119709/71ee733a-ab8a-40b7-a010-bfda76f7b1e5)

2024-01-22 15:13 UTC, ijayhub commented
I used CLI not manual installation

2024-01-23 14:49 UTC, BekahHW commented
@ijayhub apologies for that. I saw you checked a box about adding manually. 

Last thing, just provide the screenshot and it should be good to go.

2024-01-24 19:37 UTC, adiati98 commented
Hey @ijayhub,

We have merged a PR before yours. Please [resolve the conflicts](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=merge-conflicts-in-the-guestbook-repository) before we can merge yours.

And please let us know if you need any help 😊

2024-01-24 19:44 UTC, ijayhub commented
![screenshot OpenSauced](https://github.com/open-sauced/guestbook/assets/66119709/673c6ad3-46da-446d-8b2a-3891d1c57860)

2024-01-24 20:07 UTC, adiati98 commented
> ![screenshot OpenSauced](https://private-user-images.githubusercontent.com/66119709/299438375-673c6ad3-46da-446d-8b2a-3891d1c57860.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMjY2NDAsIm5iZiI6MTcwNjEyNjM0MCwicGF0aCI6Ii82NjExOTcwOS8yOTk0MzgzNzUtNjczYzZhZDMtNDZkYS00NDZkLThiMmEtMzg5MWQxYzU3ODYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDE5NTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhN2RjYWUxZDVlYzUzMzQwZjM5ZjQ3ZTU4NTRhYjNhYzE4YWY5YzNkNDFiNGQ0ZTliYjU0N2U2ZDBjMTE0NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nBZGYKgQd_e2_p3qbWX1cIWDnf1lETvKiAx5HlxPYco) @BekahHW

What do you mean, @ijayhub?

2024-01-24 21:33 UTC, ijayhub commented
😊
![Screenshoot OpenSauced1](https://github.com/open-sauced/guestbook/assets/66119709/ee666e0c-a7a8-44c3-805a-86520a313ce0) @BekahHW @adiati98

2024-01-24 21:36 UTC, BekahHW commented
@ijayhub looking good so far. Make sure you fill out the PR template though. ![image](https://github.com/open-sauced/guestbook/assets/34313413/a704ccb3-5724-48b0-92a7-9d0c79482d83)

2024-01-24 22:23 UTC, adiati98 requested changes
@ijayhub I left a review for you to fix here. :)

Then, there are a couple of things:

- After you fix it, please run the `npm run contributors:generate` as what mentioned in [the step 3 of the instruction](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=resolving-merge-conflicts). I don't see the number of contributors on the badge is changing here.
- Please answer all questions in the PR form and put your screenshot in there, too.

Thank you! Please let us know if you have any questions.

2024-01-24 22:23 UTC, adiati98 commented on .all-contributorsrc
>        "login": "Kaz-Smino",
There should be an opening bracket here.

```suggestion
   },
   {
      "login": "Kaz-Smino",
```

2024-01-26 19:29 UTC, adiati98 approved these changes
Well done, @ijayhub! 🙌
Thank you for the changes! 😄

If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P). 😊
Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕 

![git merge GIF](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

2024-01-26 21:29 UTC, BekahHW approved these changes

2024-01-26 21:29 UTC, merged