Bug: Incorrect links and term's consistency on the README #245 are fixed
open-sauced/guestbook pull request #251
Opened 2024-04-04 20:18 UTC by safaanilatasoy

## Description

## What type of PR is this? (check all applicable)

- [ ] 🤝 Add a contributor
- [x ] 📝 Documentation Update

## Contributors checklist (check all applicable)

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) section.

- [x ] ✅ Yes
- [ ] ❌ Not yet

### How did you add yourself as a contributor?

- [x ] 🤖 With CLI
- [ ] ⌨️ Manually

#### If you added yourself manually, did you follow the [emoji key and contribution types](https://allcontributors.org/docs/en/emoji-key) to fill in the value?

- [ ] ✅ Yes
- [ ] ❌ No

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?
- [x ] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [x ] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot (Required for PR Review)

![contributor](https://github.com/open-sauced/guestbook/assets/61758061/67a19d72-8448-4d25-8711-a9b33fa4fb27)

## [optional] What GIF best describes this PR or how it makes you feel?

📖📖

2024-04-04 20:46 UTC, adiati98 requested changes
Hey @safaanilatasoy,
Thank you for working on this! ✨

I see that you have a commit to add yourself to the guestbook here. You can see your commits [here](https://github.com/open-sauced/guestbook/pull/251/commits).
And there are also some things that I need you to fix:

1. Please revert the commit to add yourself to the guestbook. You can read [this blogpost](https://dev.to/github/how-to-undo-pushed-commits-with-git-2pe6) to do so.
2. Please fill in the "Description" section. We need this info to review your PR.
3. Please change your title to `fix: incorrect links and term's consistency on the README` for clarity.

Please let me know if you have any questions. Once you're done, do let me and Bekah know so we can review your PR. Thanks! 😊

2024-04-05 09:37 UTC, safaanilatasoy commented
@adiati98 hi, I made the corrections you mentioned. I'm ready for a review. thank you for your time 😄 🚀

2024-04-05 19:28 UTC, adiati98 approved these changes
Well done, @safaanilatasoy! 🙌
Thank you for the changes! 😄

![git merge GIF](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

2024-04-09 15:22 UTC, BekahHW approved these changes

2024-04-09 18:35 UTC, merged