Feat/add woytsekj
open-sauced/guestbook pull request #258
Opened 2024-04-19 20:20 UTC by Woytsekj

## Description

## What type of PR is this? (check all applicable)

- [ ] 🤝 Add a contributor
- [x] 📝 Documentation Update

## Related Issues
Closes #241

## Contributors checklist (check all applicable)

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) section.

- [x] ✅ Yes
- [ ] ❌ Not yet

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?
- [x] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [x] 📜 PULL_REQUEST_TEMPLATE.md

## Screenshot (Required for PR Review)
![image](https://github.com/open-sauced/guestbook/assets/76233345/4599be48-ba59-4be7-a4ca-dde454ffcb92)
![image](https://github.com/open-sauced/guestbook/assets/76233345/3e85421e-83b3-46d0-b704-e4e277660a3b)
![image](https://github.com/open-sauced/guestbook/assets/76233345/ef9668fe-02a5-4458-997c-5efb0281f38b)

## [optional] What GIF best describes this PR or how it makes you feel?
😃

2024-04-20 06:25 UTC, adiati98 requested changes
Hi @Woytsekj ,
Thank you for your PR! 🙌

However, please complete your PR form so we can understand and review the changes you made.

That said, please provide a description of the changes that you made,

We're only reviewing this PR once we get all the information needed.
Please let us know once you've completed the form.

Thank you. 🙂

2024-04-20 06:41 UTC, adiati98 requested changes
Hey @Woytsekj,
I've left some reviews here.

Please let me know if you've fixed them.

Thank you.

2024-04-20 06:41 UTC, adiati98 commented on .github/PULL_REQUEST_TEMPLATE.md
>  ## Description
Add a new line (space) between line 1 and 2.

2024-04-20 06:41 UTC, adiati98 commented on .github/PULL_REQUEST_TEMPLATE.md
> +## Contributors checklist
Let's capitalize this

```suggestion
## Contributors Checklist
```

2024-04-20 06:41 UTC, adiati98 commented on .github/PULL_REQUEST_TEMPLATE.md
> +### I've read through the [Getting Started](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source?id=getting-started) section.
We recently updated our course. So, please change the link with the below:

```suggestion
### I've read through the [Getting Started](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started) section.
```

2024-04-20 06:41 UTC, adiati98 commented on .github/PULL_REQUEST_TEMPLATE.md
>  - [ ] ✅ Yes
Add a new line (space) between line 28 and 29.

2024-04-20 14:36 UTC, Woytsekj commented
Hi @adiati98,

I have read the reviews and fixed them.
I have also edited my pull request to have a description.

Thank you for reminding me.

2024-04-20 15:22 UTC, BekahHW approved these changes

2024-04-21 04:37 UTC, adiati98 approved these changes

2024-04-21 04:38 UTC, merged