feat: add @JohnMwendwa as a contributor
open-sauced/guestbook pull request #269
Opened 2024-04-30 17:04 UTC by JohnMwendwa

## Description
This PR adds JohnMwendwa as a contributor.

## What type of PR is this? (check all applicable)

- [x] 🤝 Add a contributor
- [ ] 📝 Documentation Update

## Related Issues
Closes #266 

## Contributors Checklist

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started) section.

- [x] ✅ Yes
- [ ] ❌ Not yet

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?

- [x] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [x] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot (Required for PR Review)
![JohnMwendwa-screenshot](https://github.com/open-sauced/guestbook/assets/72663882/c42d216e-f435-40ed-988d-ddde6fcaed04)

## [optional] What GIF best describes this PR or how it makes you feel?
![](https://media.giphy.com/media/fUQ4rhUZJYiQsas6WD/giphy.gif?cid=82a1493bwfxzjnemueiol0vdui8d29crlkhw90rmd3otc5s5&ep=v1_gifs_trending&rid=giphy.gif&ct=g)

2024-05-01 06:30 UTC, adiati98 requested changes
Hi @JohnMwendwa,
Thank you for your PR! 🙌

However, please complete your PR form so we can understand and review the changes you made.

Can you please:
- provide a **description** of the changes that you made,

We're only reviewing and accepting this PR once we get all the information needed.
Please let us know once you've completed the form.

Thank you! 🙂

2024-05-01 07:50 UTC, adiati98 approved these changes

2024-05-08 19:22 UTC, BekahHW commented
![git merge](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOXFnZm5kN2gxcWJkeThqc21heHozODh3dXY4d3Z6a29pZnVmcWhleiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/cFkiFMDg3iFoI/giphy.gif)

Great job, @JohnMwendwa!

2024-05-08 19:24 UTC, BekahHW approved these changes

2024-05-08 19:24 UTC, merged