Feat/test
open-sauced/guestbook pull request #339
Opened 2024-05-27 16:19 UTC by chydeepak7

## Description
This is the test file 

## What type of PR is this? (check all applicable)

- [ ] 🤝 Add a contributor
- [ ] 📝 Documentation Update

## Related Issues
Fixes #337 

## Contributors Checklist

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started) section.

- [ ] ✅ Yes
- [ ] ❌ Not yet

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?

- [ ] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot (Required for PR Review)
![image](https://github.com/open-sauced/guestbook/assets/144728684/b818cd6d-fcab-4431-bdf6-84f0925b0671)

## [optional] What GIF best describes this PR or how it makes you feel?

2024-05-27 17:20 UTC, adiati98 requested changes
Hey @chydeepak7,

Thank you for your contribution! ✨ 

There are a few things here:

- There are failed checks that you can [read here](https://github.com/open-sauced/guestbook/pull/339#pullrequestreview-2081237187). Please read the bot messages and fix the problems until all check pass.
- You opened two PRs. Please close one that you don't use because they are duplication.
- **Very Important:**  You [last commit](https://github.com/open-sauced/guestbook/pull/339/commits/76250a08d648d6c14aa8d5f985cd8bb5cf25b572) deleted the `README.md` and modify the `package-lock.json`. This action will break the production. Please revert the commit. You can read [this blog post](https://dev.to/github/how-to-undo-pushed-commits-with-git-2pe6) to do so.

2024-05-27 17:46 UTC, chydeepak7 commented
Hello @adiati98 ,
I have deleted the duplicated PR and also reverted the last commit. Can you please check if I have done something wrong.
And as for the bot message I am not able to understand what its saying can you give me a clue of what I should do?

2024-05-27 18:11 UTC, chydeepak7 commented
package-lock.json how do i revert it I dont know in which commit i changed it

2024-05-27 18:17 UTC, adiati98 commented
@chydeepak7, look at the last point in my previous comment. I link your commit there.

2024-05-27 18:19 UTC, adiati98 commented
As for the only bot message left, it's saying that you modified the `package-lock.json`, and a maintainer should carefully review it.

In this case, we (maintainers) don't want to modify this file at all. That's why you need to revert the file. 🙂

2024-05-27 18:21 UTC, chydeepak7 commented
I think all the checks have passed now.

2024-05-27 19:06 UTC, adiati98 requested changes
Hey @chydeepak7,

When you resolve conflicts, you need to remove the `<<<`, `===`, and `>>>`.

After you address all the reviews, don't forget run the command to generate your profile again in your terminal because now the states are change.

2024-05-27 19:06 UTC, adiati98 commented on README.md
> +>>>>>>> parent of 76250a0 (some minor changes)
There's a duplication for the badge here. You need to remove line 47-49.

2024-05-27 19:18 UTC, chydeepak7 commented on README.md
> +>>>>>>> parent of 76250a0 (some minor changes)
I checked my README.md but there are no such changes as shown above.

2024-05-27 19:27 UTC, chydeepak7 commented on README.md
> +>>>>>>> parent of 76250a0 (some minor changes)
I tried in github codespace and those lines are showing. But in my vs code those lines are absent. Why is that??

2024-05-27 19:49 UTC, adiati98 commented
Hey @chydeepak7 
You haven't run the generate command. 

Please address all the suggestions before requesting for review. 🙂

2024-05-27 20:08 UTC, chydeepak7 commented
> Hey @chydeepak7 You haven't run the generate command.
> 
> Please address all the suggestions before requesting for review. 🙂

I just did it right now.

2024-05-27 21:17 UTC, adiati98 commented
@chydeepak7 I see that the badge is not increasing.
Have you run the `npm run contributors:generate` command in your terminal?

2024-05-27 21:23 UTC, chydeepak7 commented
> @chydeepak7 I see that the badge is missing instead of increasing. Have you run the `npm run contributors:generate` command in your terminal?

yes

2024-05-28 09:37 UTC, adiati98 approved these changes
Well done, @chydeepak7! ✨ 

If you haven't, you can join our community [Discord](https://discord.com/invite/U2peSNf23P).

![git merge GIF](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

2024-05-28 09:37 UTC, merged

2024-05-28 09:56 UTC, chydeepak7 commented
Thank you for your time and guidance