feat: add @franklinjpt as a contributor
open-sauced/guestbook pull request #375
Opened 2024-07-06 01:25 UTC by franklinjpt

## Description

## What type of PR is this? (check all applicable)

- [X] 🤝 Add a contributor
- [X] 📝 Documentation Update

## Related Issues

## Contributors Checklist

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started) section.

- [X] ✅ Yes
- [ ] ❌ Not yet

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?

- [X] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [X] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot (Required for PR Review)

[![open-sauced-profile.jpg](https://i.postimg.cc/FKPts8VK/open-sauced-profile.jpg)](https://postimg.cc/jWJ3M89V)

## [optional] What GIF best describes this PR or how it makes you feel?

2024-07-06 09:10 UTC, adiati98 requested changes
Hey @franklinjpt,

Thank you for your contribution! ✨ 

You have [failed checks](https://github.com/open-sauced/guestbook/pull/375#pullrequestreview-2161348487) that you need to address before we can review your PR. Please fix each of them until all checks pass.

You also need to provide the description of your PR in the "Description" section of your PR template.

Let me know once you've fixed them, or if you have questions or need help.

Thank you. 🙂

2024-07-06 18:27 UTC, franklinjpt commented
> Hey @franklinjpt,
> 
> Thank you for your contribution! ✨
> 
> You have [failed checks](https://github.com/open-sauced/guestbook/pull/375#pullrequestreview-2161348487) that you need to address before we can review your PR. Please fix each of them until all checks pass.
> 
> You also need to provide the description of your PR in the "Description" section of your PR template.
> 
> Let me know once you've fixed them, or if you have questions or need help.
> 
> Thank you. 🙂

Hi @adiati98 I already made the changes. Is there something else I shoul do let me know.

Thank you

2024-07-11 11:49 UTC, adiati98 approved these changes

2024-07-17 14:54 UTC, BekahHW commented
@franklinjpt thanks for your Pull Request! We've merged in some new PRs since you submitted. Can you merge the latest changes and resolve conflicts? If you need some help with that, check out this post: [Keeping Your Branch Up to Date and Handling Merge Conflicts While Waiting for PR Reviews](https://dev.to/opensauced/keeping-your-branch-up-to-date-and-handling-merge-conflicts-while-waiting-for-pr-reviews-3b3h).

2024-10-04 14:46 UTC, BekahHW approved these changes

2024-10-07 13:57 UTC, merged