feat: add @mrcentimetre as a contributor
open-sauced/guestbook pull request #381
Opened 2024-07-11 03:51 UTC by mrcentimetre

## Description

This PR adds @mrcentimetre as a contributor.

## What type of PR is this? (check all applicable)

- [x] 🤝 Add a contributor
- [ ] 📝 Documentation Update

## Related Issues

Closes #380

## Contributors Checklist

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started) section.

- [x] ✅ Yes
- [ ] ❌ Not yet

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?

- [x] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [x] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot (Required for PR Review)

<img width="119" alt="image" src="https://github.com/open-sauced/guestbook/assets/74942413/35ef0336-5239-432e-9582-118699562199">

## [optional] What GIF best describes this PR or how it makes you feel?

<img align="left" alt="GIF" height="160px" src="https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExbHB6OWY1dXo1eTEzcnlucHJtYzkyaWFzNnZxOG1iZTIyamE0NzViZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ChpOyeacGmpQk/giphy.webp" />

2024-07-11 13:58 UTC, BekahHW commented
Hey @mrcentimetre, this looks great! We've merged in some new PRs since you submitted. Can you merge the latest changes and resolve conflicts? If you need some help with that, check out this post: [Keeping Your Branch Up to Date and Handling Merge Conflicts While Waiting for PR Reviews](https://dev.to/opensauced/keeping-your-branch-up-to-date-and-handling-merge-conflicts-while-waiting-for-pr-reviews-3b3h).

2024-09-06 09:20 UTC, adiati98 requested changes
Hey @mrcentimetre,

We have merged some PRs before yours. Please [resolve the conflicts](https://opensauced.pizza/learn/intro-to-oss/how-to-contribute-to-open-source#merge-conflicts-in-the-guestbook-repository) before we can further review your PR.

Please let me know if you need any help. Thanks. 😊

2024-10-30 15:42 UTC, adiati98 approved these changes

2024-11-11 19:19 UTC, BekahHW approved these changes

2024-11-11 20:46 UTC, merged