feat: Add @zairacodes as a contributor
open-sauced/guestbook pull request #410
Opened 2024-07-26 17:52 UTC by zairacodes

## Description

This PR adds @zairacodes as a contributor.

## What type of PR is this? (check all applicable)

- [x] 🤝 Add a contributor
- [x] 📝 Documentation Update

## Related Issues

Closes #409

## Contributors Checklist

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started) section.

- [x] ✅ Yes
- [ ] ❌ Not yet

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?

- [x] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [x] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot (Required for PR Review)

<img width="176" alt="screenshot" src="https://github.com/user-attachments/assets/142e2809-2828-4c7e-b269-c8c49b6e1e2d">

## [optional] What GIF best describes this PR or how it makes you feel?

![gif](https://github.com/user-attachments/assets/f5c55b7d-9a48-481a-aae7-dcdebd1a61ef)

2024-09-04 12:30 UTC, BekahHW requested changes
Hey @zairacodes, sorry for the delay in response. This is almost right. Did you run the npm contributors generate command? It should also update the shield in the Readme with the number of contributors, and that's not reflected here.

2024-09-04 20:15 UTC, zairacodes commented
Hey @BekahHW, thank you very much for reviewing my PR! It should be correct now, could you please take a look?
Thanks again!

2024-09-12 15:28 UTC, BekahHW approved these changes

2024-09-14 21:07 UTC, adiati98 approved these changes
Well done and thank you for your contribution, @zairacodes! ✨ 

If you haven't, you can join our [Community](https://github.com/orgs/open-sauced/discussions/1).
Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕🍴

![git merge GIF](https://media.giphy.com/media/cFkiFMDg3iFoI/giphy.gif)

2024-09-14 21:08 UTC, merged