feat: Add @mohanamisra as a contributor
open-sauced/guestbook pull request #554
Opened 2024-11-01 17:21 UTC by mohanamisra

## Description
Adding user @mohanamisra (yours truly) as a contributor to this repository, as required in the Intro to Open Source course by OpenSauced.

## What type of PR is this? (check all applicable)

- [x] 🤝 Add a contributor
- [ ] 📝 Documentation Update

## Related Issues
Closes Issue #553 

## Contributors Checklist

### I've read through the [Getting Started](https://intro.opensauced.pizza/#/intro-to-oss/how-to-contribute-to-open-source?id=getting-started) section

- [x] ✅ Yes
- [ ] ❌ Not yet

### Have you run `npm run contributors:generate` to generate your profile and the badge on the README?

- [x] ✅ Yes
- [ ] ❌ No

## Added to documentation?

- [x] 📜 README.md
- [ ] 🙅 no documentation needed

## Screenshot (Required for PR Review)

  
![image](https://github.com/user-attachments/assets/66630abc-44d8-493d-abb7-0010565ad449)

## [optional] What GIF best describes this PR or how it makes you feel?
  
![68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f776174747061642d6d656469612d736572766963652f53746f7279496d6167652f386568486d71734a3135344d58773d3d2d3839373430373335352e313631353131313165363838653639643535343336363133343637372e676966](https://github.com/user-attachments/assets/f3f955e1-ea42-4369-a87f-670d1ab6ba7d)

2024-11-01 20:33 UTC, BekahHW commented
Hey @mohanamisra there's a slight change you need in the issue `Closes Issue #553`, but you need to remove the word "issue" because it breaks the key word `closes` from the issue number. So you'll need to edit that part of your PR description to `closes #553`.

2024-11-02 05:42 UTC, mohanamisra commented
> Hey @mohanamisra there's a slight change you need in the issue `Closes Issue #553`, but you need to remove the word "issue" because it breaks the key word `closes` from the issue number. So you'll need to edit that part of your PR description to `closes #553`.

Made the required change. Awaiting review!

2024-11-02 16:34 UTC, adiati98 requested changes
Hi @mohanamisra,
Thank you for your contribution! ✨ 

However, there are new files that we don't want to have here. Please remove them.

Let us know when it's fixed and ready for a review.
Thank you. 🙂

2024-11-02 16:34 UTC, adiati98 commented on .idea/.gitignore
Please remove this file.

2024-11-02 16:34 UTC, adiati98 commented on .idea/guestbook.iml
Please remove this file.

2024-11-02 16:34 UTC, adiati98 commented on .idea/modules.xml
Please remove this file.

2024-11-02 16:34 UTC, adiati98 commented on .idea/vcs.xml
Please remove this file.

2024-11-02 17:27 UTC, mohanamisra commented
> However, there are new files that we don't want to have here. Please remove them.
> 
> Let us know when it's fixed and ready for a review. Thank you. 🙂

I apologise for that !
 Removed the extra files as requested.

2024-11-04 16:48 UTC, adiati98 approved these changes
Well done and thank you for your contribution, @mohanamisra! ✨ 

If you haven't, you can join our [Community](https://github.com/orgs/open-sauced/discussions/1).
Also, check out our [pizza-verse](https://github.com/open-sauced/pizza-verse) repo if you want to contribute further! 🍕🍴

![well done GIF](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExYXhpeXgwZjQwdGNpbXA5YmR1d3R0d3h3N3Izc3ppMjFocmJ1cDJ2aSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ZdUnQS4AXEl1AERdil/giphy.gif)

2024-11-04 17:46 UTC, BekahHW approved these changes

2024-11-04 21:17 UTC, merged